version: '3.8'

services:
  app:
    build: 
      context: .
    image: app
    volumes:
      - .:/usr/nucleus/app
      - /app/node_modules
    ports:
      - 3000:3000  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
