version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:3001"
    environment:
      NODE_ENV: production
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /usr/atomus/nucleus/landing/build:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
